[2023-10-31T15:03:05.714729+00:00 INFO] [plan:278] ################################################################################
[2023-10-31T15:03:05.714924+00:00 INFO] [plan:282] Starting Reliably experiment: https://app.reliably.com/api/v1/organization/8b5fddfd-1da8-4586-934b-f184f0ef7904/experiments/e2780fca-6e1b-4fb7-87c6-976c373bfe9a/raw
[2023-10-31T15:03:05.715053+00:00 DEBUG] [__init__:201] Loading global control 'reliably-integration-slack'
[2023-10-31T15:03:05.835578+00:00 DEBUG] [__init__:201] Loading global control 'reliably-integration-opentelemetry'
[2023-10-31T15:03:07.193409+00:00 DEBUG] [caching:24] Building activity cache...
[2023-10-31T15:03:07.193597+00:00 DEBUG] [caching:35] Cached 6 activities
[2023-10-31T15:03:07.193866+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-10-31T15:03:07.194167+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-10-31T15:03:07.194485+00:00 DEBUG] [secret:78] Loading secrets...
[2023-10-31T15:03:07.194576+00:00 DEBUG] [secret:103] Done loading secrets
[2023-10-31T15:03:09.218347+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-10-31T15:03:09.218503+00:00 INFO] [experiment:109] Experiment looks valid
[2023-10-31T15:03:09.218577+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-10-31T15:03:09.218680+00:00 DEBUG] [caching:24] Building activity cache...
[2023-10-31T15:03:09.218753+00:00 DEBUG] [caching:35] Cached 6 activities
[2023-10-31T15:03:09.218892+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-10-31T15:03:09.219085+00:00 DEBUG] [secret:78] Loading secrets...
[2023-10-31T15:03:09.219150+00:00 DEBUG] [secret:103] Done loading secrets
[2023-10-31T15:03:09.219213+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-10-31T15:03:09.219404+00:00 INFO] [run:369] Running experiment: Front Service Pod Restart on Cordonned Node
[2023-10-31T15:03:09.222378+00:00 DEBUG] [run:793] 1 activities will be run in the background
[2023-10-31T15:03:09.222537+00:00 DEBUG] [__init__:166] Initializing global control 'reliably-integration-slack'
[2023-10-31T15:03:09.222624+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py' does not declare 'configure_control'
[2023-10-31T15:03:09.222687+00:00 DEBUG] [__init__:166] Initializing global control 'reliably-integration-opentelemetry'
[2023-10-31T15:03:09.222759+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py'
[2023-10-31T15:03:09.241695+00:00 INFO] [oltp:432] Chaos Toolkit Open Telemetry tracer created
[2023-10-31T15:03:09.243874+00:00 DEBUG] [oltp:144] Starting capturing OLTP traces
[2023-10-31T15:03:09.262865+00:00 DEBUG] [__init__:59] Initializing controls
[2023-10-31T15:03:09.263009+00:00 DEBUG] [__init__:68] Initializing control 'reliably'
[2023-10-31T15:03:09.263099+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-10-31T15:03:09.263246+00:00 DEBUG] [experiment:412] Configure Reliably's experiment control
[2023-10-31T15:03:09.266111+00:00 DEBUG] [experiment:589] Sending plan 'e16d8159-30ee-47a3-b8af-2ff5d21e36c6' status: running
[2023-10-31T15:03:10.447138+00:00 INFO] [experiment:195] Reliably execution: d0e832f9-9501-4a86-92fc-e6a7e0fe985d
[2023-10-31T15:03:10.856493+00:00 DEBUG] [experiment:614] Sending execution state: {'current': 'running', 'started_on': '2023-10-31T15:03:09.263319+00:00', 'plan_id': 'e16d8159-30ee-47a3-b8af-2ff5d21e36c6'}
[2023-10-31T15:03:11.285161+00:00 DEBUG] [experiment:72] Starting Reliably state checker now
[2023-10-31T15:03:11.285320+00:00 INFO] [run:396] Steady-state strategy: default
[2023-10-31T15:03:11.286609+00:00 INFO] [run:400] Rollbacks strategy: default
[2023-10-31T15:03:11.286828+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'experiment'
[2023-10-31T15:03:11.287050+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:11.509767+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'experiment'
[2023-10-31T15:03:11.509949+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_experiment_control'
[2023-10-31T15:03:11.510135+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'experiment'
[2023-10-31T15:03:11.510221+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-10-31T15:03:11.510500+00:00 DEBUG] [run:563] Running steady-state hypothesis before the method
[2023-10-31T15:03:11.511140+00:00 INFO] [hypothesis:186] Steady state hypothesis: Steady-State Hypothesis
[2023-10-31T15:03:11.511318+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'hypothesis'
[2023-10-31T15:03:11.511515+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-10-31T15:03:11.511592+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'hypothesis'
[2023-10-31T15:03:11.511764+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-10-31T15:03:11.511828+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'hypothesis'
[2023-10-31T15:03:11.512525+00:00 DEBUG] [python:196] Control 'before_hypothesis_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:11.771311+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'hypothesis'
[2023-10-31T15:03:11.771498+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_hypothesis_control'
[2023-10-31T15:03:11.771635+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:11.771734+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:11.771801+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:11.771871+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:11.771930+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:11.772001+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:12.022753+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:12.022937+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_activity_control'
[2023-10-31T15:03:12.023032+00:00 INFO] [activity:215] Probe: load-test-result-field-should-be-less-than
[2023-10-31T15:03:12.395341+00:00 DEBUG] [python:33] Activity 'load-test-result-field-should-be-less-than' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/activities/load/probes.py'
[2023-10-31T15:03:12.395707+00:00 DEBUG] [activity:237]   => succeeded with 'True'
[2023-10-31T15:03:12.783365+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:12.783634+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:12.783721+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:12.783807+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:12.783873+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:12.783951+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:13.495903+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:13.496094+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_activity_control'
[2023-10-31T15:03:13.496192+00:00 DEBUG] [hypothesis:228] allowed tolerance is True
[2023-10-31T15:03:13.496276+00:00 INFO] [hypothesis:238] Steady state hypothesis is met!
[2023-10-31T15:03:13.496380+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'hypothesis'
[2023-10-31T15:03:13.496454+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-10-31T15:03:13.497570+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'hypothesis'
[2023-10-31T15:03:13.497936+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-10-31T15:03:13.498160+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'hypothesis'
[2023-10-31T15:03:13.498245+00:00 DEBUG] [python:196] Control 'after_hypothesis_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:14.150201+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'hypothesis'
[2023-10-31T15:03:14.150392+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_hypothesis_control'
[2023-10-31T15:03:14.150697+00:00 INFO] [run:677] Playing your experiment's method now...
[2023-10-31T15:03:14.151141+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'method'
[2023-10-31T15:03:14.151443+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-10-31T15:03:14.151630+00:00 DEBUG] [activity:137] activity will run in the background
[2023-10-31T15:03:14.152117+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:14.152265+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:14.153024+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:14.153093+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:14.153159+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:14.153231+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:14.153302+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:14.152905+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:14.155591+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:14.155685+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:14.155751+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:14.155820+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:14.398835+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:14.399033+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_activity_control'
[2023-10-31T15:03:14.399668+00:00 INFO] [activity:209] Action: inject-gradual-traffic-into-endpoint [in background]
[2023-10-31T15:03:14.405429+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:14.406035+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_activity_control'
[2023-10-31T15:03:14.406668+00:00 INFO] [activity:215] Action: cordon-node
[2023-10-31T15:03:15.016767+00:00 DEBUG] [python:33] Activity 'inject-gradual-traffic-into-endpoint' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/activities/load/actions.py'
[2023-10-31T15:03:15.017727+00:00 DEBUG] [activity:294] Activity failed
Traceback (most recent call last):
  File "/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
    return func(**arguments)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/activities/load/actions.py", line 62, in inject_gradual_traffic_into_endpoint
    raise ActivityFailed("missing load test dependency")
chaoslib.exceptions.ActivityFailed: missing load test dependency

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaoslib/activity.py", line 287, in run_activity
    result = run_python_activity(activity, configuration, secrets)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
    raise ActivityFailed(
  File "/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
    return func(**arguments)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/activities/load/actions.py", line 62, in inject_gradual_traffic_into_endpoint
    raise ActivityFailed("missing load test dependency")
chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: missing load test dependency
[2023-10-31T15:03:15.023009+00:00 ERROR] [activity:245]   => failed: chaoslib.exceptions.ActivityFailed: missing load test dependency
[2023-10-31T15:03:15.026664+00:00 DEBUG] [python:33] Activity 'cordon-node' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosk8s/node/actions.py'
[2023-10-31T15:03:15.027195+00:00 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/tmp/tmpxcogvaop/tmp/kubeconfig'
[2023-10-31T15:03:15.055533+00:00 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/tmp/tmpxcogvaop/tmp/kubeconfig'
[2023-10-31T15:03:15.088013+00:00 DEBUG] [actions:55] Filtering nodes by label kubernetes.io/hostname=ip-192-168-84-116.eu-central-1.compute.internal
[2023-10-31T15:03:15.426946+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:15.427156+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:15.427684+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:15.427771+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:15.427839+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:15.427911+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:15.533182+00:00 DEBUG] [actions:57] Found 1 nodes
[2023-10-31T15:03:15.533462+00:00 DEBUG] [actions:91] Picked nodes 'ip-192-168-84-116.eu-central-1.compute.internal'
[2023-10-31T15:03:15.957427+00:00 DEBUG] [activity:239]   => succeeded without any result value
[2023-10-31T15:03:15.988182+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:15.988589+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_activity_control'
[2023-10-31T15:03:16.390676+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:16.390886+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:16.390963+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:16.391033+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:16.391095+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:16.391169+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:17.611521+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:17.611720+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_activity_control'
[2023-10-31T15:03:17.611869+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:17.611955+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:17.612020+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:17.612105+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:17.612169+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:17.612239+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:17.906389+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:17.906599+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_activity_control'
[2023-10-31T15:03:17.906706+00:00 INFO] [activity:215] Action: pause-execution
[2023-10-31T15:03:18.393082+00:00 DEBUG] [python:33] Activity 'pause-execution' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/activities/pauses.py'
[2023-10-31T15:03:18.393401+00:00 INFO] [pauses:23] Pausing activity for 30s or until the execution is resumed
[2023-10-31T15:03:48.393639+00:00 INFO] [pauses:26] Resuming execution...
[2023-10-31T15:03:48.393873+00:00 DEBUG] [activity:239]   => succeeded without any result value
[2023-10-31T15:03:48.863560+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:48.863760+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:48.863941+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:48.864026+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:48.864088+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:48.864160+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:49.578730+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:49.578926+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_activity_control'
[2023-10-31T15:03:49.579566+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:49.579658+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:49.579723+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:49.579789+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:49.579849+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:49.579919+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:49.798590+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:49.798779+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_activity_control'
[2023-10-31T15:03:49.799073+00:00 INFO] [activity:215] Probe: get-nodes
[2023-10-31T15:03:50.545071+00:00 DEBUG] [python:33] Activity 'get-nodes' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosk8s/node/probes.py'
[2023-10-31T15:03:50.545453+00:00 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/tmp/tmpxcogvaop/tmp/kubeconfig'
[2023-10-31T15:03:51.106745+00:00 DEBUG] [activity:237]   => succeeded with '{'kind': 'NodeList', 'apiVersion': 'v1', 'metadata': {'resourceVersion': '57942897'}, 'items': [{'metadata': {'name': 'ip-192-168-27-96.eu-central-1.compute.internal', 'uid': '8aab9ebd-2d55-45e7-b5b3-ed4e49858629', 'resourceVersion': '57941407', 'creationTimestamp': '2023-10-31T14:55:13Z', 'labels': {'alpha.eksctl.io/cluster-name': 'amazing-sheepdog-1681288074', 'alpha.eksctl.io/nodegroup-name': 'ng-241dcd04', 'beta.kubernetes.io/arch': 'amd64', 'beta.kubernetes.io/instance-type': 't2.medium', 'beta.kubernetes.io/os': 'linux', 'eks.amazonaws.com/capacityType': 'ON_DEMAND', 'eks.amazonaws.com/nodegroup': 'ng-241dcd04', 'eks.amazonaws.com/nodegroup-image': 'ami-0448154a5db05c605', 'eks.amazonaws.com/sourceLaunchTemplateId': 'lt-069a9db772572d134', 'eks.amazonaws.com/sourceLaunchTemplateVersion': '1', 'failure-domain.beta.kubernetes.io/region': 'eu-central-1', 'failure-domain.beta.kubernetes.io/zone': 'eu-central-1a', 'k8s.io/cloud-provider-aws': 'c8ac3001d948700e9e19b64aec821dba', 'kubernetes.io/arch': 'amd64', 'kubernetes.io/hostname': 'ip-192-168-27-96.eu-central-1.compute.internal', 'kubernetes.io/os': 'linux', 'node.kubernetes.io/instance-type': 't2.medium', 'topology.kubernetes.io/region': 'eu-central-1', 'topology.kubernetes.io/zone': 'eu-central-1a'}, 'annotations': {'alpha.kubernetes.io/provided-node-ip': '192.168.27.96', 'node.alpha.kubernetes.io/ttl': '0', 'volumes.kubernetes.io/controller-managed-attach-detach': 'true'}, 'managedFields': [{'manager': 'aws-cloud-controller-manager', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-31T14:55:14Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:status': {'f:addresses': {'k:{"type":"ExternalDNS"}': {'.': {}, 'f:address': {}, 'f:type': {}}, 'k:{"type":"ExternalIP"}': {'.': {}, 'f:address': {}, 'f:type': {}}, 'k:{"type":"InternalDNS"}': {'.': {}, 'f:address': {}, 'f:type': {}}}}}}, {'manager': 'kube-controller-manager', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-31T14:55:25Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'f:node.alpha.kubernetes.io/ttl': {}}}}}, {'manager': 'kubelet', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-31T14:58:49Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:status': {'f:conditions': {'k:{"type":"DiskPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"MemoryPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"PIDPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"Ready"}': {'f:lastHeartbeatTime': {}, 'f:lastTransitionTime': {}, 'f:message': {}, 'f:reason': {}, 'f:status': {}}}, 'f:images': {}}}, 'subresource': 'status'}]}, 'spec': {'providerID': 'aws:///eu-central-1a/i-0ef4961396882fe05'}, 'status': {'capacity': {'cpu': '2', 'ephemeral-storage': '83873772Ki', 'hugepages-2Mi': '0', 'memory': '4001664Ki', 'pods': '17'}, 'allocatable': {'cpu': '1930m', 'ephemeral-storage': '76224326324', 'hugepages-2Mi': '0', 'memory': '3446656Ki', 'pods': '17'}, 'conditions': [{'type': 'MemoryPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T14:58:49Z', 'lastTransitionTime': '2023-10-31T14:55:12Z', 'reason': 'KubeletHasSufficientMemory', 'message': 'kubelet has sufficient memory available'}, {'type': 'DiskPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T14:58:49Z', 'lastTransitionTime': '2023-10-31T14:55:12Z', 'reason': 'KubeletHasNoDiskPressure', 'message': 'kubelet has no disk pressure'}, {'type': 'PIDPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T14:58:49Z', 'lastTransitionTime': '2023-10-31T14:55:12Z', 'reason': 'KubeletHasSufficientPID', 'message': 'kubelet has sufficient PID available'}, {'type': 'Ready', 'status': 'True', 'lastHeartbeatTime': '2023-10-31T14:58:49Z', 'lastTransitionTime': '2023-10-31T14:55:25Z', 'reason': 'KubeletReady', 'message': 'kubelet is posting ready status'}], 'addresses': [{'type': 'InternalIP', 'address': '192.168.27.96'}, {'type': 'ExternalIP', 'address': '52.29.193.54'}, {'type': 'InternalDNS', 'address': 'ip-192-168-27-96.eu-central-1.compute.internal'}, {'type': 'Hostname', 'address': 'ip-192-168-27-96.eu-central-1.compute.internal'}, {'type': 'ExternalDNS', 'address': 'ec2-52-29-193-54.eu-central-1.compute.amazonaws.com'}], 'daemonEndpoints': {'kubeletEndpoint': {'Port': 10250}}, 'nodeInfo': {'machineID': 'f3fea62ec12840fd812fde8f2a10f35c', 'systemUUID': 'ec2064ae-df19-ff0c-6fb4-9fdbe3890b60', 'bootID': '4e1e9f90-382a-463d-861a-3f3754beccf8', 'kernelVersion': '5.10.192-183.736.amzn2.x86_64', 'osImage': 'Amazon Linux 2', 'containerRuntimeVersion': 'containerd://1.6.19', 'kubeletVersion': 'v1.27.5-eks-43840fb', 'kubeProxyVersion': 'v1.27.5-eks-43840fb', 'operatingSystem': 'linux', 'architecture': 'amd64'}, 'images': [{'names': ['ghcr.io/chaos-mesh/chaos-daemon@sha256:e77a434eb7ae5f7ced3dd151eb58c5abdbb6216c82d213ae8c8c6bc348f789e3', 'ghcr.io/chaos-mesh/chaos-daemon:v2.6.2'], 'sizeBytes': 249481489}, {'names': ['ghcr.io/open-telemetry/demo@sha256:8d54660097ecfa30220a0643f26b7c9a3cd591aaf5463a2267488ceacc2e4123', 'ghcr.io/open-telemetry/demo:1.5.0-frontend'], 'sizeBytes': 171520497}, {'names': ['docker.io/lawouach/rbly@sha256:9e875c8fc8367ce9c6fed283d7dd11b28f55be88b89027b276ad59acae93fa3c', 'docker.io/lawouach/rbly:latest'], 'sizeBytes': 158057434}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.15.0-eksbuild.2'], 'sizeBytes': 59729985}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.15.0-eksbuild.2'], 'sizeBytes': 45015981}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.12.6-eksbuild.2'], 'sizeBytes': 42862707}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni@sha256:4523827f651b5bc17c63c1239b668647d107db7a9616ea5f1d15c1f43f915530', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.12.2-eksbuild.1'], 'sizeBytes': 40373013}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.27.1-minimal-eksbuild.1'], 'sizeBytes': 29980152}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.27.6-minimal-eksbuild.2'], 'sizeBytes': 29976345}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy@sha256:7d1ed1e2f1f2ba5ca729a9d5417ff7db799390b6b2360edb8074d6758ca69987', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.25.6-minimal-eksbuild.1'], 'sizeBytes': 25694113}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.12.6-eksbuild.2'], 'sizeBytes': 22202900}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni-init@sha256:1f7b8278accfd89c63dc4c02d77f2d78c608c3ac1bf2a4d6c22c371a891ce2fe', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni-init:v1.12.2-eksbuild.1'], 'sizeBytes': 21845483}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.5', '602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5'], 'sizeBytes': 298689}]}}, {'metadata': {'name': 'ip-192-168-31-98.eu-central-1.compute.internal', 'uid': 'c944da12-856f-4c40-bc44-16670734d287', 'resourceVersion': '57942541', 'creationTimestamp': '2023-10-26T21:10:36Z', 'labels': {'alpha.eksctl.io/cluster-name': 'amazing-sheepdog-1681288074', 'alpha.eksctl.io/nodegroup-name': 'ng-241dcd04', 'beta.kubernetes.io/arch': 'amd64', 'beta.kubernetes.io/instance-type': 't2.medium', 'beta.kubernetes.io/os': 'linux', 'eks.amazonaws.com/capacityType': 'ON_DEMAND', 'eks.amazonaws.com/nodegroup': 'ng-241dcd04', 'eks.amazonaws.com/nodegroup-image': 'ami-0448154a5db05c605', 'eks.amazonaws.com/sourceLaunchTemplateId': 'lt-069a9db772572d134', 'eks.amazonaws.com/sourceLaunchTemplateVersion': '1', 'failure-domain.beta.kubernetes.io/region': 'eu-central-1', 'failure-domain.beta.kubernetes.io/zone': 'eu-central-1a', 'k8s.io/cloud-provider-aws': 'c8ac3001d948700e9e19b64aec821dba', 'kubernetes.io/arch': 'amd64', 'kubernetes.io/hostname': 'ip-192-168-31-98.eu-central-1.compute.internal', 'kubernetes.io/os': 'linux', 'node.kubernetes.io/instance-type': 't2.medium', 'topology.kubernetes.io/region': 'eu-central-1', 'topology.kubernetes.io/zone': 'eu-central-1a'}, 'annotations': {'alpha.kubernetes.io/provided-node-ip': '192.168.31.98', 'node.alpha.kubernetes.io/ttl': '0', 'volumes.kubernetes.io/controller-managed-attach-detach': 'true'}, 'managedFields': [{'manager': 'aws-cloud-controller-manager', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-26T21:10:37Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:status': {'f:addresses': {'k:{"type":"ExternalDNS"}': {'.': {}, 'f:address': {}, 'f:type': {}}, 'k:{"type":"ExternalIP"}': {'.': {}, 'f:address': {}, 'f:type': {}}, 'k:{"type":"InternalDNS"}': {'.': {}, 'f:address': {}, 'f:type': {}}}}}}, {'manager': 'kube-controller-manager', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-27T20:41:40Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'f:node.alpha.kubernetes.io/ttl': {}}}}}, {'manager': 'kubelet', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-31T15:02:39Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:status': {'f:conditions': {'k:{"type":"DiskPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"MemoryPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"PIDPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"Ready"}': {'f:lastHeartbeatTime': {}, 'f:lastTransitionTime': {}, 'f:message': {}, 'f:reason': {}, 'f:status': {}}}, 'f:images': {}}}, 'subresource': 'status'}]}, 'spec': {'providerID': 'aws:///eu-central-1a/i-02afa55bbb10342bc'}, 'status': {'capacity': {'cpu': '2', 'ephemeral-storage': '83873772Ki', 'hugepages-2Mi': '0', 'memory': '4001664Ki', 'pods': '17'}, 'allocatable': {'cpu': '1930m', 'ephemeral-storage': '76224326324', 'hugepages-2Mi': '0', 'memory': '3446656Ki', 'pods': '17'}, 'conditions': [{'type': 'MemoryPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T15:02:39Z', 'lastTransitionTime': '2023-10-26T21:10:35Z', 'reason': 'KubeletHasSufficientMemory', 'message': 'kubelet has sufficient memory available'}, {'type': 'DiskPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T15:02:39Z', 'lastTransitionTime': '2023-10-26T21:10:35Z', 'reason': 'KubeletHasNoDiskPressure', 'message': 'kubelet has no disk pressure'}, {'type': 'PIDPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T15:02:39Z', 'lastTransitionTime': '2023-10-26T21:10:35Z', 'reason': 'KubeletHasSufficientPID', 'message': 'kubelet has sufficient PID available'}, {'type': 'Ready', 'status': 'True', 'lastHeartbeatTime': '2023-10-31T15:02:39Z', 'lastTransitionTime': '2023-10-26T21:10:49Z', 'reason': 'KubeletReady', 'message': 'kubelet is posting ready status'}], 'addresses': [{'type': 'InternalIP', 'address': '192.168.31.98'}, {'type': 'ExternalIP', 'address': '18.159.97.35'}, {'type': 'InternalDNS', 'address': 'ip-192-168-31-98.eu-central-1.compute.internal'}, {'type': 'Hostname', 'address': 'ip-192-168-31-98.eu-central-1.compute.internal'}, {'type': 'ExternalDNS', 'address': 'ec2-18-159-97-35.eu-central-1.compute.amazonaws.com'}], 'daemonEndpoints': {'kubeletEndpoint': {'Port': 10250}}, 'nodeInfo': {'machineID': '93f2dad06da1490683942826b2654417', 'systemUUID': 'ec2cc011-46d0-af12-748c-d4288cce8596', 'bootID': 'e2e757cb-d445-4f44-9d86-f9ce844adc27', 'kernelVersion': '5.10.192-183.736.amzn2.x86_64', 'osImage': 'Amazon Linux 2', 'containerRuntimeVersion': 'containerd://1.6.19', 'kubeletVersion': 'v1.27.5-eks-43840fb', 'kubeProxyVersion': 'v1.27.5-eks-43840fb', 'operatingSystem': 'linux', 'architecture': 'amd64'}, 'images': [{'names': ['ghcr.io/open-telemetry/demo@sha256:eea585753ae48821f590325127640dbf18e00dc378db4938e472877e52af6137', 'ghcr.io/open-telemetry/demo:1.5.0-kafka'], 'sizeBytes': 463361601}, {'names': ['ghcr.io/chaos-mesh/chaos-daemon@sha256:e77a434eb7ae5f7ced3dd151eb58c5abdbb6216c82d213ae8c8c6bc348f789e3', 'ghcr.io/chaos-mesh/chaos-daemon:v2.6.2'], 'sizeBytes': 249481489}, {'names': ['ghcr.io/open-telemetry/demo@sha256:8d54660097ecfa30220a0643f26b7c9a3cd591aaf5463a2267488ceacc2e4123', 'ghcr.io/open-telemetry/demo:1.5.0-frontend'], 'sizeBytes': 171520497}, {'names': ['ghcr.io/open-telemetry/demo@sha256:d4122076ee281ad576f1e58cc8b19ec3ae7cb3c8972d3df50500ed9dc782d4df', 'ghcr.io/open-telemetry/demo:1.5.0-adservice'], 'sizeBytes': 159540293}, {'names': ['ghcr.io/open-telemetry/demo@sha256:7c04f9d2d79c6852a9716f9fef4c407a90fe5444d1a25074f31ccd458f5fdb71', 'ghcr.io/open-telemetry/demo:1.5.0-frauddetectionservice'], 'sizeBytes': 137474760}, {'names': ['quay.io/prometheus/prometheus@sha256:c5dd3503828713c4949ae1bccd1d8d69f382c33d441954674a6b78ebe69c3331', 'quay.io/prometheus/prometheus:v2.47.0'], 'sizeBytes': 98169067}, {'names': ['docker.io/grafana/grafana@sha256:423040d62678074111e4e72d7dcef23480a94eb4f21b9173204d1a5ee972ec59', 'docker.io/grafana/grafana:10.0.3'], 'sizeBytes': 93701256}, {'names': ['docker.io/lawouach/consumer@sha256:32a7cda64b1771c4b21922d400ece8066a99037cd80452b29f5a445b5d4d38ed', 'docker.io/lawouach/consumer:latest'], 'sizeBytes': 66439076}, {'names': ['ghcr.io/open-telemetry/demo@sha256:a1cbe7b54ff78bdd04e12c18889b0054db522fc946e8c79f583579b4673263a3', 'ghcr.io/open-telemetry/demo:1.5.0-paymentservice'], 'sizeBytes': 61091808}, {'names': ['ghcr.io/open-telemetry/demo@sha256:d91b85450cfd3cb8cb1f7d2d8705f9a73af7228de8a035b7ae9fe892b09ffe20', 'ghcr.io/open-telemetry/demo:1.5.0-recommendationservice'], 'sizeBytes': 60485612}, {'names': ['docker.io/otel/opentelemetry-collector-contrib@sha256:566cac13663e966330df755b113e80d267117425457c117cec2937415fa18ef9', 'docker.io/otel/opentelemetry-collector-contrib:0.85.0'], 'sizeBytes': 60139701}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.15.0-eksbuild.2'], 'sizeBytes': 59729985}, {'names': ['docker.io/lawouach/web@sha256:e871a00c4737fbb40843c8e585db2890e58bc1ef749baad03acd7df4fb0a5d5d', 'docker.io/lawouach/web:latest'], 'sizeBytes': 57022589}, {'names': ['ghcr.io/open-telemetry/demo@sha256:9646df027bda4c44b6b8f6a3106390e04065daee3f36759e887c4a184f210a2c', 'ghcr.io/open-telemetry/demo:1.5.0-frontendproxy'], 'sizeBytes': 56622902}, {'names': ['ghcr.io/open-telemetry/demo@sha256:e8e326005831c3c9d7040fb7f6dc44f6d2b7def3ad6277413e6efd855fdee8c7', 'ghcr.io/open-telemetry/demo:1.5.0-featureflagservice'], 'sizeBytes': 47894269}, {'names': ['ghcr.io/open-telemetry/demo@sha256:285373b0cbbf58a197d4daee17a6eec028fca7cf74200010a5b9e6950204a149', 'ghcr.io/open-telemetry/demo:1.5.0-cartservice'], 'sizeBytes': 45558128}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.15.0-eksbuild.2'], 'sizeBytes': 45015981}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.12.6-eksbuild.2'], 'sizeBytes': 42862707}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni@sha256:4523827f651b5bc17c63c1239b668647d107db7a9616ea5f1d15c1f43f915530', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.12.2-eksbuild.1'], 'sizeBytes': 40373013}, {'names': ['ghcr.io/open-telemetry/demo@sha256:2e67db2dc28c50935a2cd518fa14a42ab3e253c0fe8dcbe00dd1d8cb2bcabdea', 'ghcr.io/open-telemetry/demo:1.5.0-shippingservice'], 'sizeBytes': 40020292}, {'names': ['public.ecr.aws/aws-observability/adot-operator@sha256:851fed45e5fb417952c463c0df4130cbeabe6d63dfc84e3c1673c7e23382bd3f', 'public.ecr.aws/aws-observability/adot-operator:v0.70.0'], 'sizeBytes': 36205339}, {'names': ['public.ecr.aws/aws-observability/aws-otel-collector@sha256:1a625e4e92e8032ad0fee99b0064d7f349757ac6ed7b1f5d4ddd31eac4939470', 'public.ecr.aws/aws-observability/aws-otel-collector:v0.26.1'], 'sizeBytes': 30752238}, {'names': ['docker.io/jaegertracing/all-in-one@sha256:5d5c9d2d8c8cbb42f1db4aac1f1f8487bac63da6802004d0da8580fc0c7311a1', 'docker.io/jaegertracing/all-in-one:1.45.0'], 'sizeBytes': 30359605}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.27.1-minimal-eksbuild.1'], 'sizeBytes': 29980152}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.27.6-minimal-eksbuild.2'], 'sizeBytes': 29976345}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy@sha256:7d1ed1e2f1f2ba5ca729a9d5417ff7db799390b6b2360edb8074d6758ca69987', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.25.6-minimal-eksbuild.1'], 'sizeBytes': 25694113}, {'names': ['public.ecr.aws/aws-observability/mirror-kube-rbac-proxy@sha256:d99a8d144816b951a67648c12c0b988936ccd25cf3754f3cd85ab8c01592248f', 'public.ecr.aws/aws-observability/mirror-kube-rbac-proxy:v0.13.0'], 'sizeBytes': 25405613}, {'names': ['ghcr.io/chaos-mesh/chaos-mesh@sha256:5da3544f524d2fd15c5dbd8b0daedd31e080f37fac4b7cd4b39566f946a9b8bd', 'ghcr.io/chaos-mesh/chaos-mesh:v2.6.2'], 'sizeBytes': 24478938}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.12.6-eksbuild.2'], 'sizeBytes': 22202900}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni-init@sha256:1f7b8278accfd89c63dc4c02d77f2d78c608c3ac1bf2a4d6c22c371a891ce2fe', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni-init:v1.12.2-eksbuild.1'], 'sizeBytes': 21845483}, {'names': ['quay.io/jetstack/cert-manager-controller@sha256:d429b6d696e0ef47cff1d15241c6ffaac351e38ac22664b82fafa771d615b89a', 'quay.io/jetstack/cert-manager-controller:v1.11.0'], 'sizeBytes': 18256020}, {'names': ['public.ecr.aws/eks/aws-load-balancer-controller@sha256:186050ef1e0a9cefd9fde045bdb3dbd300aa743322c8ab693992f81da612cc22', 'public.ecr.aws/eks/aws-load-balancer-controller:v2.4.7'], 'sizeBytes': 17540236}, {'names': ['docker.io/library/redis@sha256:2d44eb73209e5af4118de67e89b01709bfec7cc5a4c1cec29665f6d011c70783', 'docker.io/library/redis:alpine'], 'sizeBytes': 16036195}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/coredns@sha256:283e342425558e69cc2e709337347e446d20604f544b2f98dd6f03dab7cd805a', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/coredns:v1.9.3-eksbuild.2'], 'sizeBytes': 14964386}, {'names': ['ghcr.io/open-telemetry/demo@sha256:af9235593238c7d0c5d5694cf6e305ccbedea115e7e45d5e89f3389c3d090c5c', 'ghcr.io/open-telemetry/demo:1.5.0-accountingservice'], 'sizeBytes': 13972641}, {'names': ['quay.io/jetstack/cert-manager-cainjector@sha256:5c3eb25b085443b83586a98a1ae07f8364461dfca700e950c30f585efb7474ba', 'quay.io/jetstack/cert-manager-cainjector:v1.11.0'], 'sizeBytes': 12570894}, {'names': ['ghcr.io/open-telemetry/demo@sha256:1e935211b247814aebb9b0220ed6e6bb9e68eba3caceceebcfbd47aded0d2070', 'ghcr.io/open-telemetry/demo:1.5.0-productcatalogservice'], 'sizeBytes': 12007816}, {'names': ['docker.io/library/busybox@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79', 'docker.io/library/busybox:latest'], 'sizeBytes': 2224229}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.5', '602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5'], 'sizeBytes': 298689}]}}, {'metadata': {'name': 'ip-192-168-84-116.eu-central-1.compute.internal', 'uid': '6375d3f1-9beb-43bd-89d6-c263e84227f9', 'resourceVersion': '57942788', 'creationTimestamp': '2023-10-29T12:56:56Z', 'labels': {'alpha.eksctl.io/cluster-name': 'amazing-sheepdog-1681288074', 'alpha.eksctl.io/nodegroup-name': 'ng-241dcd04', 'beta.kubernetes.io/arch': 'amd64', 'beta.kubernetes.io/instance-type': 't2.medium', 'beta.kubernetes.io/os': 'linux', 'eks.amazonaws.com/capacityType': 'ON_DEMAND', 'eks.amazonaws.com/nodegroup': 'ng-241dcd04', 'eks.amazonaws.com/nodegroup-image': 'ami-0448154a5db05c605', 'eks.amazonaws.com/sourceLaunchTemplateId': 'lt-069a9db772572d134', 'eks.amazonaws.com/sourceLaunchTemplateVersion': '1', 'failure-domain.beta.kubernetes.io/region': 'eu-central-1', 'failure-domain.beta.kubernetes.io/zone': 'eu-central-1c', 'k8s.io/cloud-provider-aws': 'c8ac3001d948700e9e19b64aec821dba', 'kubernetes.io/arch': 'amd64', 'kubernetes.io/hostname': 'ip-192-168-84-116.eu-central-1.compute.internal', 'kubernetes.io/os': 'linux', 'node.kubernetes.io/instance-type': 't2.medium', 'topology.kubernetes.io/region': 'eu-central-1', 'topology.kubernetes.io/zone': 'eu-central-1c'}, 'annotations': {'alpha.kubernetes.io/provided-node-ip': '192.168.84.116', 'node.alpha.kubernetes.io/ttl': '0', 'volumes.kubernetes.io/controller-managed-attach-detach': 'true'}, 'managedFields': [{'manager': 'aws-cloud-controller-manager', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-29T12:56:56Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:status': {'f:addresses': {'k:{"type":"ExternalDNS"}': {'.': {}, 'f:address': {}, 'f:type': {}}, 'k:{"type":"ExternalIP"}': {'.': {}, 'f:address': {}, 'f:type': {}}, 'k:{"type":"InternalDNS"}': {'.': {}, 'f:address': {}, 'f:type': {}}}}}}, {'manager': 'OpenAPI-Generator', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-31T15:03:15Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {'f:unschedulable': {}}}}, {'manager': 'kube-controller-manager', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-31T15:03:15Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'f:node.alpha.kubernetes.io/ttl': {}}}, 'f:spec': {'f:taints': {}}}}, {'manager': 'kubelet', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-31T15:03:29Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:status': {'f:conditions': {'k:{"type":"DiskPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"MemoryPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"PIDPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"Ready"}': {'f:lastHeartbeatTime': {}, 'f:lastTransitionTime': {}, 'f:message': {}, 'f:reason': {}, 'f:status': {}}}, 'f:images': {}}}, 'subresource': 'status'}]}, 'spec': {'providerID': 'aws:///eu-central-1c/i-039b0e93737780329', 'unschedulable': True, 'taints': [{'key': 'node.kubernetes.io/unschedulable', 'effect': 'NoSchedule', 'timeAdded': '2023-10-31T15:03:15Z'}]}, 'status': {'capacity': {'cpu': '2', 'ephemeral-storage': '83873772Ki', 'hugepages-2Mi': '0', 'memory': '4001664Ki', 'pods': '17'}, 'allocatable': {'cpu': '1930m', 'ephemeral-storage': '76224326324', 'hugepages-2Mi': '0', 'memory': '3446656Ki', 'pods': '17'}, 'conditions': [{'type': 'MemoryPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T15:03:29Z', 'lastTransitionTime': '2023-10-29T12:56:55Z', 'reason': 'KubeletHasSufficientMemory', 'message': 'kubelet has sufficient memory available'}, {'type': 'DiskPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T15:03:29Z', 'lastTransitionTime': '2023-10-29T12:56:55Z', 'reason': 'KubeletHasNoDiskPressure', 'message': 'kubelet has no disk pressure'}, {'type': 'PIDPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T15:03:29Z', 'lastTransitionTime': '2023-10-29T12:56:55Z', 'reason': 'KubeletHasSufficientPID', 'message': 'kubelet has sufficient PID available'}, {'type': 'Ready', 'status': 'True', 'lastHeartbeatTime': '2023-10-31T15:03:29Z', 'lastTransitionTime': '2023-10-29T12:57:09Z', 'reason': 'KubeletReady', 'message': 'kubelet is posting ready status'}], 'addresses': [{'type': 'InternalIP', 'address': '192.168.84.116'}, {'type': 'ExternalIP', 'address': '3.68.101.110'}, {'type': 'InternalDNS', 'address': 'ip-192-168-84-116.eu-central-1.compute.internal'}, {'type': 'Hostname', 'address': 'ip-192-168-84-116.eu-central-1.compute.internal'}, {'type': 'ExternalDNS', 'address': 'ec2-3-68-101-110.eu-central-1.compute.amazonaws.com'}], 'daemonEndpoints': {'kubeletEndpoint': {'Port': 10250}}, 'nodeInfo': {'machineID': '2209fd096c8742f8bc06a81a6987e041', 'systemUUID': 'ec219f29-db38-d55c-7d00-e3f825bb3db8', 'bootID': '6e897d73-ca8a-40f7-ba8b-a43476f852b7', 'kernelVersion': '5.10.192-183.736.amzn2.x86_64', 'osImage': 'Amazon Linux 2', 'containerRuntimeVersion': 'containerd://1.6.19', 'kubeletVersion': 'v1.27.5-eks-43840fb', 'kubeProxyVersion': 'v1.27.5-eks-43840fb', 'operatingSystem': 'linux', 'architecture': 'amd64'}, 'images': [{'names': ['ghcr.io/open-telemetry/demo@sha256:eea585753ae48821f590325127640dbf18e00dc378db4938e472877e52af6137', 'ghcr.io/open-telemetry/demo:1.5.0-kafka'], 'sizeBytes': 463361601}, {'names': ['ghcr.io/chaos-mesh/chaos-daemon@sha256:e77a434eb7ae5f7ced3dd151eb58c5abdbb6216c82d213ae8c8c6bc348f789e3', 'ghcr.io/chaos-mesh/chaos-daemon:v2.6.2'], 'sizeBytes': 249481489}, {'names': ['ghcr.io/open-telemetry/demo@sha256:8d54660097ecfa30220a0643f26b7c9a3cd591aaf5463a2267488ceacc2e4123', 'ghcr.io/open-telemetry/demo:1.5.0-frontend'], 'sizeBytes': 171520497}, {'names': ['docker.io/lawouach/rbly@sha256:9e875c8fc8367ce9c6fed283d7dd11b28f55be88b89027b276ad59acae93fa3c', 'docker.io/lawouach/rbly:latest'], 'sizeBytes': 158057434}, {'names': ['docker.io/library/postgres@sha256:8f7ae11760980811fd91845f89fcf6e01801b9b08f7d72a6796e1bee1e0098fb', 'docker.io/library/postgres:14'], 'sizeBytes': 147679365}, {'names': ['ghcr.io/open-telemetry/demo@sha256:7c04f9d2d79c6852a9716f9fef4c407a90fe5444d1a25074f31ccd458f5fdb71', 'ghcr.io/open-telemetry/demo:1.5.0-frauddetectionservice'], 'sizeBytes': 137474760}, {'names': ['ghcr.io/open-telemetry/demo@sha256:5e476180c56367897ffafa532e880878c96445b374b8586bcde9c67f135f3e1f', 'ghcr.io/open-telemetry/demo:1.5.0-currencyservice'], 'sizeBytes': 137297480}, {'names': ['docker.io/lawouach/consumer@sha256:32a7cda64b1771c4b21922d400ece8066a99037cd80452b29f5a445b5d4d38ed', 'docker.io/lawouach/consumer:latest'], 'sizeBytes': 66439076}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.15.0-eksbuild.2'], 'sizeBytes': 59729985}, {'names': ['ghcr.io/open-telemetry/demo@sha256:9646df027bda4c44b6b8f6a3106390e04065daee3f36759e887c4a184f210a2c', 'ghcr.io/open-telemetry/demo:1.5.0-frontendproxy'], 'sizeBytes': 56622902}, {'names': ['ghcr.io/open-telemetry/demo@sha256:285373b0cbbf58a197d4daee17a6eec028fca7cf74200010a5b9e6950204a149', 'ghcr.io/open-telemetry/demo:1.5.0-cartservice'], 'sizeBytes': 45558128}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.15.0-eksbuild.2'], 'sizeBytes': 45015981}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.12.6-eksbuild.2'], 'sizeBytes': 42862707}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni@sha256:4523827f651b5bc17c63c1239b668647d107db7a9616ea5f1d15c1f43f915530', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.12.2-eksbuild.1'], 'sizeBytes': 40373013}, {'names': ['ghcr.io/open-telemetry/demo@sha256:2e67db2dc28c50935a2cd518fa14a42ab3e253c0fe8dcbe00dd1d8cb2bcabdea', 'ghcr.io/open-telemetry/demo:1.5.0-shippingservice'], 'sizeBytes': 40020292}, {'names': ['docker.io/jaegertracing/all-in-one@sha256:5d5c9d2d8c8cbb42f1db4aac1f1f8487bac63da6802004d0da8580fc0c7311a1', 'docker.io/jaegertracing/all-in-one:1.45.0'], 'sizeBytes': 30359605}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.27.1-minimal-eksbuild.1'], 'sizeBytes': 29980152}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.27.6-minimal-eksbuild.2'], 'sizeBytes': 29976345}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy@sha256:7d1ed1e2f1f2ba5ca729a9d5417ff7db799390b6b2360edb8074d6758ca69987', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.25.6-minimal-eksbuild.1'], 'sizeBytes': 25694113}, {'names': ['ghcr.io/chaos-mesh/chaos-mesh@sha256:5da3544f524d2fd15c5dbd8b0daedd31e080f37fac4b7cd4b39566f946a9b8bd', 'ghcr.io/chaos-mesh/chaos-mesh:v2.6.2'], 'sizeBytes': 24478938}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.12.6-eksbuild.2'], 'sizeBytes': 22202900}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni-init@sha256:1f7b8278accfd89c63dc4c02d77f2d78c608c3ac1bf2a4d6c22c371a891ce2fe', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni-init:v1.12.2-eksbuild.1'], 'sizeBytes': 21845483}, {'names': ['docker.io/library/redis@sha256:2d44eb73209e5af4118de67e89b01709bfec7cc5a4c1cec29665f6d011c70783', 'docker.io/library/redis:alpine'], 'sizeBytes': 16036195}, {'names': ['ghcr.io/open-telemetry/demo@sha256:f90369fba680171ebe52ace640c07c98d9f962fdb82c5b27a3edfd15b7c41358', 'ghcr.io/open-telemetry/demo:1.5.0-checkoutservice'], 'sizeBytes': 14894064}, {'names': ['quay.io/jetstack/cert-manager-webhook@sha256:6730d96fc382a57cde4f7519d2a32b40013e0d3bace2ea0579c7c051fbbd608d', 'quay.io/jetstack/cert-manager-webhook:v1.11.0'], 'sizeBytes': 14293497}, {'names': ['ghcr.io/open-telemetry/demo@sha256:af9235593238c7d0c5d5694cf6e305ccbedea115e7e45d5e89f3389c3d090c5c', 'ghcr.io/open-telemetry/demo:1.5.0-accountingservice'], 'sizeBytes': 13972641}, {'names': ['quay.io/jetstack/cert-manager-cainjector@sha256:5c3eb25b085443b83586a98a1ae07f8364461dfca700e950c30f585efb7474ba', 'quay.io/jetstack/cert-manager-cainjector:v1.11.0'], 'sizeBytes': 12570894}, {'names': ['docker.io/library/busybox@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79', 'docker.io/library/busybox:latest'], 'sizeBytes': 2224229}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.5', '602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5'], 'sizeBytes': 298689}]}}, {'metadata': {'name': 'ip-192-168-88-36.eu-central-1.compute.internal', 'uid': '576bf4cc-03c9-47da-93b4-1a8c32c21fc9', 'resourceVersion': '57942064', 'creationTimestamp': '2023-10-26T21:10:37Z', 'labels': {'alpha.eksctl.io/cluster-name': 'amazing-sheepdog-1681288074', 'alpha.eksctl.io/nodegroup-name': 'ng-241dcd04', 'beta.kubernetes.io/arch': 'amd64', 'beta.kubernetes.io/instance-type': 't2.medium', 'beta.kubernetes.io/os': 'linux', 'eks.amazonaws.com/capacityType': 'ON_DEMAND', 'eks.amazonaws.com/nodegroup': 'ng-241dcd04', 'eks.amazonaws.com/nodegroup-image': 'ami-0448154a5db05c605', 'eks.amazonaws.com/sourceLaunchTemplateId': 'lt-069a9db772572d134', 'eks.amazonaws.com/sourceLaunchTemplateVersion': '1', 'failure-domain.beta.kubernetes.io/region': 'eu-central-1', 'failure-domain.beta.kubernetes.io/zone': 'eu-central-1c', 'k8s.io/cloud-provider-aws': 'c8ac3001d948700e9e19b64aec821dba', 'kubernetes.io/arch': 'amd64', 'kubernetes.io/hostname': 'ip-192-168-88-36.eu-central-1.compute.internal', 'kubernetes.io/os': 'linux', 'node.kubernetes.io/instance-type': 't2.medium', 'topology.kubernetes.io/region': 'eu-central-1', 'topology.kubernetes.io/zone': 'eu-central-1c'}, 'annotations': {'alpha.kubernetes.io/provided-node-ip': '192.168.88.36', 'node.alpha.kubernetes.io/ttl': '0', 'volumes.kubernetes.io/controller-managed-attach-detach': 'true'}, 'managedFields': [{'manager': 'aws-cloud-controller-manager', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-26T21:10:37Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:status': {'f:addresses': {'k:{"type":"ExternalDNS"}': {'.': {}, 'f:address': {}, 'f:type': {}}, 'k:{"type":"ExternalIP"}': {'.': {}, 'f:address': {}, 'f:type': {}}, 'k:{"type":"InternalDNS"}': {'.': {}, 'f:address': {}, 'f:type': {}}}}}}, {'manager': 'kube-controller-manager', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-31T14:34:13Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'f:node.alpha.kubernetes.io/ttl': {}}}}}, {'manager': 'kubelet', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2023-10-31T15:01:02Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:status': {'f:conditions': {'k:{"type":"DiskPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"MemoryPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"PIDPressure"}': {'f:lastHeartbeatTime': {}}, 'k:{"type":"Ready"}': {'f:lastHeartbeatTime': {}, 'f:lastTransitionTime': {}, 'f:message': {}, 'f:reason': {}, 'f:status': {}}}, 'f:images': {}}}, 'subresource': 'status'}]}, 'spec': {'providerID': 'aws:///eu-central-1c/i-09e64443caa6a4247'}, 'status': {'capacity': {'cpu': '2', 'ephemeral-storage': '83873772Ki', 'hugepages-2Mi': '0', 'memory': '4001664Ki', 'pods': '17'}, 'allocatable': {'cpu': '1930m', 'ephemeral-storage': '76224326324', 'hugepages-2Mi': '0', 'memory': '3446656Ki', 'pods': '17'}, 'conditions': [{'type': 'MemoryPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T15:01:02Z', 'lastTransitionTime': '2023-10-26T21:10:35Z', 'reason': 'KubeletHasSufficientMemory', 'message': 'kubelet has sufficient memory available'}, {'type': 'DiskPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T15:01:02Z', 'lastTransitionTime': '2023-10-26T21:10:35Z', 'reason': 'KubeletHasNoDiskPressure', 'message': 'kubelet has no disk pressure'}, {'type': 'PIDPressure', 'status': 'False', 'lastHeartbeatTime': '2023-10-31T15:01:02Z', 'lastTransitionTime': '2023-10-26T21:10:35Z', 'reason': 'KubeletHasSufficientPID', 'message': 'kubelet has sufficient PID available'}, {'type': 'Ready', 'status': 'True', 'lastHeartbeatTime': '2023-10-31T15:01:02Z', 'lastTransitionTime': '2023-10-26T21:10:48Z', 'reason': 'KubeletReady', 'message': 'kubelet is posting ready status'}], 'addresses': [{'type': 'InternalIP', 'address': '192.168.88.36'}, {'type': 'ExternalIP', 'address': '3.68.71.133'}, {'type': 'InternalDNS', 'address': 'ip-192-168-88-36.eu-central-1.compute.internal'}, {'type': 'Hostname', 'address': 'ip-192-168-88-36.eu-central-1.compute.internal'}, {'type': 'ExternalDNS', 'address': 'ec2-3-68-71-133.eu-central-1.compute.amazonaws.com'}], 'daemonEndpoints': {'kubeletEndpoint': {'Port': 10250}}, 'nodeInfo': {'machineID': '8f2eae4336d549b69edb7fcceb0c9b30', 'systemUUID': 'ec26834d-98c7-fcf9-384c-abd7ded45c5f', 'bootID': '6a218bbc-02b2-47a1-a31a-02c7c0204fb4', 'kernelVersion': '5.10.192-183.736.amzn2.x86_64', 'osImage': 'Amazon Linux 2', 'containerRuntimeVersion': 'containerd://1.6.19', 'kubeletVersion': 'v1.27.5-eks-43840fb', 'kubeProxyVersion': 'v1.27.5-eks-43840fb', 'operatingSystem': 'linux', 'architecture': 'amd64'}, 'images': [{'names': ['ghcr.io/chaos-mesh/chaos-daemon@sha256:e77a434eb7ae5f7ced3dd151eb58c5abdbb6216c82d213ae8c8c6bc348f789e3', 'ghcr.io/chaos-mesh/chaos-daemon:v2.6.2'], 'sizeBytes': 249481489}, {'names': ['ghcr.io/open-telemetry/demo@sha256:1b9414c5a1e29bff9af38b0809a5e42dbd365a2e550e0303628b5e7a8a5ba2bc', 'ghcr.io/open-telemetry/demo:1.5.0-quoteservice'], 'sizeBytes': 183509541}, {'names': ['ghcr.io/open-telemetry/demo@sha256:d4122076ee281ad576f1e58cc8b19ec3ae7cb3c8972d3df50500ed9dc782d4df', 'ghcr.io/open-telemetry/demo:1.5.0-adservice'], 'sizeBytes': 159540293}, {'names': ['docker.io/library/postgres@sha256:8f7ae11760980811fd91845f89fcf6e01801b9b08f7d72a6796e1bee1e0098fb', 'docker.io/library/postgres:14'], 'sizeBytes': 147679365}, {'names': ['ghcr.io/open-telemetry/demo@sha256:7c04f9d2d79c6852a9716f9fef4c407a90fe5444d1a25074f31ccd458f5fdb71', 'ghcr.io/open-telemetry/demo:1.5.0-frauddetectionservice'], 'sizeBytes': 137474760}, {'names': ['ghcr.io/open-telemetry/demo@sha256:5e476180c56367897ffafa532e880878c96445b374b8586bcde9c67f135f3e1f', 'ghcr.io/open-telemetry/demo:1.5.0-currencyservice'], 'sizeBytes': 137297480}, {'names': ['quay.io/prometheus/prometheus@sha256:c5dd3503828713c4949ae1bccd1d8d69f382c33d441954674a6b78ebe69c3331', 'quay.io/prometheus/prometheus:v2.47.0'], 'sizeBytes': 98169067}, {'names': ['docker.io/grafana/grafana@sha256:423040d62678074111e4e72d7dcef23480a94eb4f21b9173204d1a5ee972ec59', 'docker.io/grafana/grafana:10.0.3'], 'sizeBytes': 93701256}, {'names': ['ghcr.io/open-telemetry/demo@sha256:a4bc0325894b0211bace28571cef099d16404aa22d23080378fcb753ee91a186', 'ghcr.io/open-telemetry/demo:1.5.0-emailservice'], 'sizeBytes': 88280872}, {'names': ['docker.io/lawouach/consumer@sha256:32a7cda64b1771c4b21922d400ece8066a99037cd80452b29f5a445b5d4d38ed', 'docker.io/lawouach/consumer:latest'], 'sizeBytes': 66439076}, {'names': ['docker.io/lawouach/producer@sha256:de26bfbdbdb1cb7143a5a1e37f5994b0092818a383dacfe06de9b84ce9249ecd', 'docker.io/lawouach/producer:latest'], 'sizeBytes': 65831126}, {'names': ['ghcr.io/chaos-mesh/chaos-dashboard@sha256:9e08d1e4d3180fd6c37d70b377ef412826a020344c26483f254c5e8d79f5574d', 'ghcr.io/chaos-mesh/chaos-dashboard:v2.6.2'], 'sizeBytes': 62866190}, {'names': ['ghcr.io/open-telemetry/demo@sha256:a1cbe7b54ff78bdd04e12c18889b0054db522fc946e8c79f583579b4673263a3', 'ghcr.io/open-telemetry/demo:1.5.0-paymentservice'], 'sizeBytes': 61091808}, {'names': ['ghcr.io/open-telemetry/demo@sha256:d91b85450cfd3cb8cb1f7d2d8705f9a73af7228de8a035b7ae9fe892b09ffe20', 'ghcr.io/open-telemetry/demo:1.5.0-recommendationservice'], 'sizeBytes': 60485612}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.15.0-eksbuild.2'], 'sizeBytes': 59729985}, {'names': ['ghcr.io/open-telemetry/demo@sha256:9646df027bda4c44b6b8f6a3106390e04065daee3f36759e887c4a184f210a2c', 'ghcr.io/open-telemetry/demo:1.5.0-frontendproxy'], 'sizeBytes': 56622902}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.15.0-eksbuild.2'], 'sizeBytes': 45015981}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.12.6-eksbuild.2'], 'sizeBytes': 42862707}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni@sha256:4523827f651b5bc17c63c1239b668647d107db7a9616ea5f1d15c1f43f915530', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.12.2-eksbuild.1'], 'sizeBytes': 40373013}, {'names': ['ghcr.io/open-telemetry/demo@sha256:2e67db2dc28c50935a2cd518fa14a42ab3e253c0fe8dcbe00dd1d8cb2bcabdea', 'ghcr.io/open-telemetry/demo:1.5.0-shippingservice'], 'sizeBytes': 40020292}, {'names': ['registry.k8s.io/autoscaling/cluster-autoscaler@sha256:dfbb63a82d437253febc68540ced60ed796494edf242d1d2cb5b9665570e99c0', 'registry.k8s.io/autoscaling/cluster-autoscaler:v1.27.2'], 'sizeBytes': 37241668}, {'names': ['docker.io/jaegertracing/all-in-one@sha256:5d5c9d2d8c8cbb42f1db4aac1f1f8487bac63da6802004d0da8580fc0c7311a1', 'docker.io/jaegertracing/all-in-one:1.45.0'], 'sizeBytes': 30359605}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.27.1-minimal-eksbuild.1'], 'sizeBytes': 29980152}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.27.6-minimal-eksbuild.2'], 'sizeBytes': 29976345}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy@sha256:7d1ed1e2f1f2ba5ca729a9d5417ff7db799390b6b2360edb8074d6758ca69987', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/kube-proxy:v1.25.6-minimal-eksbuild.1'], 'sizeBytes': 25694113}, {'names': ['ghcr.io/chaos-mesh/chaos-mesh@sha256:5da3544f524d2fd15c5dbd8b0daedd31e080f37fac4b7cd4b39566f946a9b8bd', 'ghcr.io/chaos-mesh/chaos-mesh:v2.6.2'], 'sizeBytes': 24478938}, {'names': ['602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.12.6-eksbuild.2'], 'sizeBytes': 22202900}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni-init@sha256:1f7b8278accfd89c63dc4c02d77f2d78c608c3ac1bf2a4d6c22c371a891ce2fe', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni-init:v1.12.2-eksbuild.1'], 'sizeBytes': 21845483}, {'names': ['quay.io/jetstack/cert-manager-controller@sha256:d429b6d696e0ef47cff1d15241c6ffaac351e38ac22664b82fafa771d615b89a', 'quay.io/jetstack/cert-manager-controller:v1.11.0'], 'sizeBytes': 18256020}, {'names': ['public.ecr.aws/eks/aws-load-balancer-controller@sha256:186050ef1e0a9cefd9fde045bdb3dbd300aa743322c8ab693992f81da612cc22', 'public.ecr.aws/eks/aws-load-balancer-controller:v2.4.7'], 'sizeBytes': 17540236}, {'names': ['docker.io/library/redis@sha256:2d44eb73209e5af4118de67e89b01709bfec7cc5a4c1cec29665f6d011c70783', 'docker.io/library/redis:alpine'], 'sizeBytes': 16036195}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/coredns@sha256:283e342425558e69cc2e709337347e446d20604f544b2f98dd6f03dab7cd805a', '602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/coredns:v1.9.3-eksbuild.2'], 'sizeBytes': 14964386}, {'names': ['ghcr.io/open-telemetry/demo@sha256:f90369fba680171ebe52ace640c07c98d9f962fdb82c5b27a3edfd15b7c41358', 'ghcr.io/open-telemetry/demo:1.5.0-checkoutservice'], 'sizeBytes': 14894064}, {'names': ['quay.io/jetstack/cert-manager-webhook@sha256:6730d96fc382a57cde4f7519d2a32b40013e0d3bace2ea0579c7c051fbbd608d', 'quay.io/jetstack/cert-manager-webhook:v1.11.0'], 'sizeBytes': 14293497}, {'names': ['ghcr.io/open-telemetry/demo@sha256:af9235593238c7d0c5d5694cf6e305ccbedea115e7e45d5e89f3389c3d090c5c', 'ghcr.io/open-telemetry/demo:1.5.0-accountingservice'], 'sizeBytes': 13972641}, {'names': ['ghcr.io/chaos-mesh/chaos-coredns@sha256:78dc63bc5b89aa3619668ba9a2870469661058c962bf0838510ee9a7f502a99a', 'ghcr.io/chaos-mesh/chaos-coredns:v0.2.6'], 'sizeBytes': 13905012}, {'names': ['quay.io/jetstack/cert-manager-cainjector@sha256:5c3eb25b085443b83586a98a1ae07f8364461dfca700e950c30f585efb7474ba', 'quay.io/jetstack/cert-manager-cainjector:v1.11.0'], 'sizeBytes': 12570894}, {'names': ['ghcr.io/open-telemetry/demo@sha256:1e935211b247814aebb9b0220ed6e6bb9e68eba3caceceebcfbd47aded0d2070', 'ghcr.io/open-telemetry/demo:1.5.0-productcatalogservice'], 'sizeBytes': 12007816}, {'names': ['docker.io/library/busybox@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79', 'docker.io/library/busybox:latest'], 'sizeBytes': 2224229}, {'names': ['602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.5', '602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5'], 'sizeBytes': 298689}]}}]}'
[2023-10-31T15:03:51.692554+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:51.692747+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:51.692819+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:51.692886+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:51.692946+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:51.693016+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:53.137791+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:53.137979+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_activity_control'
[2023-10-31T15:03:53.138122+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:53.138205+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:53.138268+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:53.138331+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:53.138502+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:53.138588+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:53.356162+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:53.356362+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_activity_control'
[2023-10-31T15:03:53.356461+00:00 INFO] [activity:215] Action: terminate-pods
[2023-10-31T15:03:53.992567+00:00 DEBUG] [python:33] Activity 'terminate-pods' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosk8s/pod/actions.py'
[2023-10-31T15:03:53.993487+00:00 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/tmp/tmpxcogvaop/tmp/kubeconfig'
[2023-10-31T15:03:54.438311+00:00 DEBUG] [actions:232] Found 1 pods labelled 'app.kubernetes.io/name=reliably-otel-demo-frontend' in ns otel
[2023-10-31T15:03:54.574855+00:00 DEBUG] [activity:237]   => succeeded with '['reliably-otel-demo-frontend-d8cbd5d9-rsk8m']'
[2023-10-31T15:03:55.216123+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:55.216323+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:55.216397+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:03:55.217280+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:03:55.217402+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:55.217486+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:56.208971+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:56.209163+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_activity_control'
[2023-10-31T15:03:56.209308+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:56.209438+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:56.209505+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:03:56.209569+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:03:56.209628+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:03:56.209697+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:03:56.462531+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:03:56.462719+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_activity_control'
[2023-10-31T15:03:56.462819+00:00 INFO] [activity:215] Action: pause-execution
[2023-10-31T15:03:57.179449+00:00 DEBUG] [python:33] Activity 'pause-execution' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/activities/pauses.py'
[2023-10-31T15:03:57.179720+00:00 INFO] [pauses:23] Pausing activity for 45s or until the execution is resumed
[2023-10-31T15:04:42.179994+00:00 INFO] [pauses:26] Resuming execution...
[2023-10-31T15:04:42.180224+00:00 DEBUG] [activity:239]   => succeeded without any result value
[2023-10-31T15:04:42.808074+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:04:42.808270+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:04:42.808345+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:04:42.808412+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:04:42.808473+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:04:42.808542+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:04:43.544256+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:04:43.545136+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_activity_control'
[2023-10-31T15:04:43.545237+00:00 DEBUG] [run:930] Waiting for background activities to complete
[2023-10-31T15:04:43.546977+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'method'
[2023-10-31T15:04:43.547099+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-10-31T15:04:43.547260+00:00 DEBUG] [run:599] Running steady-state hypothesis after the method
[2023-10-31T15:04:43.547534+00:00 INFO] [hypothesis:186] Steady state hypothesis: Steady-State Hypothesis
[2023-10-31T15:04:43.547656+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'hypothesis'
[2023-10-31T15:04:43.547733+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-10-31T15:04:43.547794+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'hypothesis'
[2023-10-31T15:04:43.547856+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-10-31T15:04:43.547914+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'hypothesis'
[2023-10-31T15:04:43.547979+00:00 DEBUG] [python:196] Control 'before_hypothesis_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:04:43.836635+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'hypothesis'
[2023-10-31T15:04:43.836820+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_hypothesis_control'
[2023-10-31T15:04:43.837526+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:04:43.837994+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:04:43.838107+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:04:43.838440+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:04:43.838561+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:04:43.838639+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:04:44.103629+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:04:44.103822+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_activity_control'
[2023-10-31T15:04:44.104401+00:00 INFO] [activity:215] Probe: load-test-result-field-should-be-less-than
[2023-10-31T15:04:45.599103+00:00 DEBUG] [python:33] Activity 'load-test-result-field-should-be-less-than' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/activities/load/probes.py'
[2023-10-31T15:04:45.599464+00:00 DEBUG] [activity:237]   => succeeded with 'True'
[2023-10-31T15:04:46.217165+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:04:46.217399+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:04:46.217480+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:04:46.217549+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:04:46.217611+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:04:46.217680+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:04:46.833714+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:04:46.833901+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_activity_control'
[2023-10-31T15:04:46.834000+00:00 DEBUG] [hypothesis:228] allowed tolerance is True
[2023-10-31T15:04:46.834077+00:00 INFO] [hypothesis:238] Steady state hypothesis is met!
[2023-10-31T15:04:46.834181+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'hypothesis'
[2023-10-31T15:04:46.834258+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-10-31T15:04:46.834321+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'hypothesis'
[2023-10-31T15:04:46.834384+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-10-31T15:04:46.834444+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'hypothesis'
[2023-10-31T15:04:46.834515+00:00 DEBUG] [python:196] Control 'after_hypothesis_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:04:47.422629+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'hypothesis'
[2023-10-31T15:04:47.422814+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_hypothesis_control'
[2023-10-31T15:04:47.423170+00:00 INFO] [run:957] Let's rollback...
[2023-10-31T15:04:47.423297+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'rollback'
[2023-10-31T15:04:47.423378+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-10-31T15:04:47.423449+00:00 INFO] [rollback:34] Rollback: uncordon-node
[2023-10-31T15:04:47.423548+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:04:47.423620+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:04:47.423678+00:00 DEBUG] [__init__:455] Applying before-control 'reliably' on 'activity'
[2023-10-31T15:04:47.423741+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-10-31T15:04:47.423799+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:04:47.423883+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:04:47.651131+00:00 DEBUG] [__init__:455] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:04:47.651357+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'before_activity_control'
[2023-10-31T15:04:47.651899+00:00 INFO] [activity:215] Action: uncordon-node
[2023-10-31T15:04:48.259300+00:00 DEBUG] [python:33] Activity 'uncordon-node' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosk8s/node/actions.py'
[2023-10-31T15:04:48.260306+00:00 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/tmp/tmpxcogvaop/tmp/kubeconfig'
[2023-10-31T15:04:48.290536+00:00 DEBUG] [__init__:73] Using Kubernetes context 'default' from config '/tmp/tmpxcogvaop/tmp/kubeconfig'
[2023-10-31T15:04:48.315195+00:00 DEBUG] [actions:55] Filtering nodes by label kubernetes.io/hostname=ip-192-168-84-116.eu-central-1.compute.internal
[2023-10-31T15:04:48.719231+00:00 DEBUG] [actions:57] Found 1 nodes
[2023-10-31T15:04:48.719848+00:00 DEBUG] [actions:91] Picked nodes 'ip-192-168-84-116.eu-central-1.compute.internal'
[2023-10-31T15:04:49.227725+00:00 DEBUG] [activity:239]   => succeeded without any result value
[2023-10-31T15:04:49.864160+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:04:49.864368+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:04:49.864877+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'activity'
[2023-10-31T15:04:49.865810+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-10-31T15:04:49.866400+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-10-31T15:04:49.866889+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:04:51.024402+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-10-31T15:04:51.024602+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_activity_control'
[2023-10-31T15:04:51.024884+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'rollback'
[2023-10-31T15:04:51.025119+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-10-31T15:04:51.025281+00:00 INFO] [run:515] Experiment ended with status: completed
[2023-10-31T15:04:51.025510+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-slack' on 'experiment'
[2023-10-31T15:04:51.025700+00:00 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-10-31T15:04:51.555809+00:00 DEBUG] [__init__:455] Applying after-control 'reliably-integration-opentelemetry' on 'experiment'
[2023-10-31T15:04:51.555996+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'after_experiment_control'
[2023-10-31T15:04:51.556180+00:00 DEBUG] [__init__:455] Applying after-control 'reliably' on 'experiment'
[2023-10-31T15:04:51.556272+00:00 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-10-31T15:04:51.765427+00:00 DEBUG] [slack:129] Capture Slack messages from #acme
[2023-10-31T15:04:51.765595+00:00 DEBUG] [slack:131] Fetching the last 300 messages for the past 2mn [2023-10-31 15:02:51.765376+00:00] from channel #acme [C057K7HCV7A]
[2023-10-31T15:04:52.306513+00:00 DEBUG] [__init__:98] Cleaning up controls
[2023-10-31T15:04:52.306691+00:00 DEBUG] [__init__:107] Cleaning up control 'reliably'
[2023-10-31T15:04:52.306895+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-10-31T15:04:52.306980+00:00 DEBUG] [__init__:260] Cleaning up global control 'reliably-integration-slack'
[2023-10-31T15:04:52.307050+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosslack/control.py' does not declare 'cleanup_control'
[2023-10-31T15:04:52.307112+00:00 DEBUG] [__init__:260] Cleaning up global control 'reliably-integration-opentelemetry'
[2023-10-31T15:04:52.307175+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaostracing/oltp.py' does not declare 'cleanup_control'
[2023-10-31T15:04:52.307238+00:00 DEBUG] [oltp:155] Stopping capturing OLTP traces
[2023-10-31T15:04:52.307372+00:00 DEBUG] [oltp:165] Finished capturing OLTP traces
[2023-10-31T15:04:52.307442+00:00 INFO] [experiment:241] Finishing Reliably execution...
[2023-10-31T15:04:52.720524+00:00 DEBUG] [experiment:154] Stopping Reliably state checker now
[2023-10-31T15:04:52.721121+00:00 DEBUG] [experiment:496] Completing execution 'd0e832f9-9501-4a86-92fc-e6a7e0fe985d' status: completed
[2023-10-31T15:04:53.870561+00:00 DEBUG] [experiment:589] Sending plan 'e16d8159-30ee-47a3-b8af-2ff5d21e36c6' status: completed
[2023-10-31T15:04:54.247290+00:00 DEBUG] [experiment:614] Sending execution state: {'current': 'finished', 'status': 'completed', 'deviated': False, 'plan_id': 'e16d8159-30ee-47a3-b8af-2ff5d21e36c6'}
[2023-10-31T15:04:54.760723+00:00 INFO] [experiment:300] Finished Reliably execution. Bye!
[2023-10-31T15:04:54.761440+00:00 DEBUG] [caching:42] Clearing activities cache
